# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsexec < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.1/ecsexec_Darwin_x86_64.tar.gz"
      sha256 "ca3ba0be42e5c75ce93811869907abe23554d70e48b968dd2fc22e951130fd32"

      def install
        bin.install "ecsexec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.1/ecsexec_Darwin_arm64.tar.gz"
      sha256 "80a3740be33783696f2d9cb769b58c30823f6c86b8e01359c8bf36c17a2e5b45"

      def install
        bin.install "ecsexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.1/ecsexec_Linux_x86_64.tar.gz"
      sha256 "746ad9229ac0c011cfb5baf7bf90a976d4fdcf45f3793a0dab48a6c3372c5d79"

      def install
        bin.install "ecsexec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.1/ecsexec_Linux_arm64.tar.gz"
      sha256 "5be9607cb0504a36edadf3b1381fad5399b676ad162b169e7f733d82462d174e"

      def install
        bin.install "ecsexec"
      end
    end
  end
end
