# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ecsexec < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.3/ecsexec_Darwin_x86_64.tar.gz"
      sha256 "dddbe6f48f193b62221d5e95195281f7d0183859960aaa341db4f41f8c7fee01"

      def install
        bin.install "ecsexec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.3/ecsexec_Darwin_arm64.tar.gz"
      sha256 "cade4cae331657ddfee1d095d3acd3853bb02a955ec7644de1222c5dfc80929d"

      def install
        bin.install "ecsexec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.3/ecsexec_Linux_x86_64.tar.gz"
      sha256 "c04658b9a8a61a1cb4055035293cb80bcd422d842dc6d2f38dc691096d3335e0"

      def install
        bin.install "ecsexec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Taiki130/ecsexec/releases/download/v0.0.3/ecsexec_Linux_arm64.tar.gz"
      sha256 "45a06e304209c9ea9743ad3b348c7fbc3bfe9baf6a9a65b197374ce2b2afa0f7"

      def install
        bin.install "ecsexec"
      end
    end
  end
end
